name: SkyWarsForPE
main: larryTheCoder\SkyWarsAPI
version: "1.8_BETA"
api: [2.0.0]
author: larryTheCoder
commands:
  sw:
    description: use /sw help for all parameters
    aliases: sk,skywars
permission:
  sw.command.lobby:
    description: back to main lobby
    default: true
  sw.acces:
    description: access the game intrance
    default: true
# For VIP access NOT DONE
#  sw.acces.full:
#    description: ability to join full game
#    default: true
  sw.editlobby:
    description: prevent players from edit lobby
    default: op
  sw.sign:
    description: join using signs 
    default: true
  sw.command:
    description: allow player to use all skywars command
    default: op
    children:
     sw.command.help:
        description: get SkyWars help menu
        default: op
     sw.command.setlobby:
        description: set SkyWars main lobby
        default: op
     sw.command.create:
        description: create a SkyWars arenas
        default: op
     sw.command.reload:
        description: reload skywars plugin
        default: op