## SkyWars Config.
---
# Game prefix
Prefix: "&b[&6Sky&aWars&b] "

# Game language message
# English
Language: English

# Game lobby location
lobby:
  spawn_x: 0
  spawn_y: 0
  spawn_z: 0
  world: world

# min players in skywars world
minplayers: 3
# max players in skywars world
maxplayers: 12
# chat format 
chat_format: true
...