name: SkyShopPE
main: larryTheCoder\SkyWarsShopAPI
version: "1.1_Alpha"
api: [2.0.0]
author: larryTheHarry

permissions:
    SkyShopPE.shop.buy:
      default: true
      description: allow to use shop
    ShyShopPE.shop.create:
      default: op
      description: allow to create a shop
      
    

